### ISSUE TITLE
Deconstruct QuerySetSequence back into QuerySets

### ISSUE THREAD

**Issue by jpic** [percipient/django-querysetsequence#21]
Since the private API changed in 6394e19, this required a fix in dal's form field https://github.com/yourlabs/django-autocomplete-light/commit/7ec8106662fde5e4591ea96143264c2d9ade264c

For the form field (#2), we need to validate a tuple of ctype id and object id against the QuerySetSequence. The current implementation deconstructs the QuerySetSequence back into querysets to validate the object id against the queryset corresponding to the ctype.

Is there any way to achieve this goal with the public API ?

**Comment by clokep** [comment]
It's unclear to me what you're trying to do. Are you trying to check if instances of `QuerySetSequence` are the same? What public API would help you?

**Comment by jpic** [comment]
The querysetsequence form field has a QuerySetSequence instance for its choices:

     some_field = QuerySetSequenceChoiceField(choices=QuerySetSequence(Foo.objects.all(), Bar.objects.all()))

That field value contains both the content type id and object id:

    <input value="1_2" ... />

Where `1` is the content type id, and `2` is the object id.

And that's how we end up needing to check if a tuple of `(ctype_id, obj_id)` represents a model that's inside a QSS instance.

It would be great if we could get the queryset for a specific ctype ie.::

    foo_qs = qss.get_for_ctype(ctype_id)

That would allow to get the initial queryset object for the given content type id, and allow running the necessary validation and all.

Does this help ?

**Comment by clokep** [comment]
Maybe. How do you know that there's only a single `QuerySet` for a particular content type though? What is `obj_id` in your example? (Is this the order of the items in the `QuerySetSequence`?)

**Comment by jpic** [comment]
Well that's an incorrect assumption I made.

The obj_id is the model instance primary key in my example.

**Comment by clokep** [comment]
I'm not really sure what to do here, so it seems like you want to be able to:
* Have a `QuerySetSequence`
* For each element get some unique tuple
* For that unique tuple you want to get back the `QuerySet` that that element was part of?

Is that correct? I think you need to use the number of the `QuerySet` inside of the `QuerySetSequence` instead of the `ContentType`.

**Comment by jpic** [comment]
I just want to know if a model is inside a queryset sequence.

Because I want to validate a forms.ChoiceField value with my widget which takes a queryset sequence for choises.

That's it ;)

**Comment by jpic** [comment]
Hello!

We're piling up compat code : 

People seem to be waring on one of my repo because the feature for this issue is only available through private api. yourlabs/django-autocomplete-light#1056

Is it possible to just add a method to know if a given model object is in

**Comment by clokep** [comment]
Touching the `_querysets` in `QuerySetSequence` is not really supported. Sorry you've had to add a bunch of hacks for it, but the way they are stored is a private API.

I think an invalid assumption is made in [the `get_queryset_for_content_type` code](https://github.com/yourlabs/django-autocomplete-light/blob/2b4338b85c3fd37d105608200cca60b135bb6012/src/dal_queryset_sequence/fields.py#L15-L38), a single model (and thus content type) could be in a `QuerySetSequence` multiple times (and actually the same object could be in the `QuerySetSequence` multiple times), e.g. the following is valid (although I don't know *why* you'd do it):

```python
sequence = QuerySetSequence(Book.objects.all(), Book.objects.all())
```

**Comment by clokep** [comment]
For what it is worth, there's is an API I've kept pretty stable that gives you the index of the `QuerySet` in the `QuerySetSequence`. A property called `'#'` is added to model instances during iteration, that might be useful to you. This seems to be supported since version 0.7.

**Comment by clokep** [comment]
I just checked this briefly and I think you'd be able to store `QuerySet` index + object ID instead of content type ID + object ID. You could then split this, like you are now, and do something like the following:

```python
queryset_index, object_id = self.get_queryset_index_object_id(val)
# I think self.queryset is actually a QuerySetSequence, but it is unclear from the code.
result = self.queryset.get(**{'#': queryset_index, 'id': object_id})
```

**Comment by jpic** [comment]
Thanks @clokep !!!

Sounds perfectly feasable, all we need to do is swap from ctypeId+objId to qsId+objId, if we need the ctype for some reason we can still get it from the qsId.

Closing for now, will reopen if necessary.

Thanks again for your kind support !

Have a great day

**Comment by clokep** [comment]
Awesome! 👍 Let me know if it doesn't work for some reason.

**Comment by optiz0r** [comment]
I've put together some code to use the qsId instead of the ctypeId which solves the first usage of the private api, however there is another usage which I can't see an easy solution for using the public api methods on the `QuerySetSequence` object:

```python
    def mixup_querysets(self, qs):
        """Return a queryset with different model types."""
        if len(list(qs.query._querysets)):
            limit = int(self.paginate_by / len(qs.query._querysets))
            qs.query._querysets[0][:2]
            qs = QuerySetSequence(*[q[:limit] for q in qs.query._querysets])
        return qs
```

This code takes a slice of upto a fixed size, taking results uniformly from each queryset within the sequence. Can you think of a way to implement this using public methods, or conversely, would you be open to adding a method that does this or something similar into the `QuerySetSequence` public api directly?

**Comment by clokep** [comment]
@optiz0r I'm not sure I 100% follow what this is doing (an example might well here!) (Knowing the use-case might also help me understand what this is doing.)

**Comment by optiz0r** [comment]
I think there's a noop line in the middle which is not helping things (it's not my code, and I'd not looked too hard at it before). I'll remove this from the paste above to make things clearer: `qs.query._querysets[0][:2]`

Imagining an ordered QuerySetSequence is formed of two QuerySets, the first of which contains 20 results, and the second 10. A `[:10]` slice of the QuerySetSequence would return the first 10 results of the first QuerySet, and none from the second, I believe. This function would return 5 from each. It's evenly distributing the pagination limit across all the constituent QuerySets, and composing a new QuerySetSequence that would return that lower limit from each type.

An example use-case is an autocomplete form field which searches both Users and UserGroups. This function aims to returns a selection of both types matching a given search term, even if normally one QuerySet would contain enough results to meet the pagination limit alone.

**Comment by clokep** [comment]
> Imagining an ordered QuerySetSequence is formed of two QuerySets, the first of which contains 20 results, and the second 10. A `[:10]` slice of the QuerySetSequence would return the first 10 results of the first QuerySet, and none from the second, I believe.

This depends on the ordering of the `QuerySetSequence`. What you describe here is the "unordered" behavior (or if you ordered by `'#'` first).

> This function would return 5 from each. It's evenly distributing the pagination limit across all the constituent QuerySets, and composing a new QuerySetSequence that would return that lower limit from each type.
> 
> An example use-case is an autocomplete form field which searches both Users and UserGroups. This function aims to returns a selection of both types matching a given search term, even if normally one QuerySet would contain enough results to meet the pagination limit alone.

Thanks, that's a reasonable use-case.

Is the goal really to give 5 from each or is it to give the "best" matches in someway or another?

**Comment by optiz0r** [comment]
A "closest" match algorithm is probably best, but might be hard to do across multiple querysets without some domain specific knowledge. I suspect distributing the selection across all querysets is the closest general case solution, but open to suggestions from both yourself and @jpic.

I don't claim to speak for all users of this code downstream, I'm just trying to fix a blocking incompatibility between multiple projects I have dependencies on.

**Comment by optiz0r** [comment]
The approach of using the queryset ID instead of the content type ID appears to be a non-starter, for the reasons described in this issue comment: https://github.com/yourlabs/django-autocomplete-light/issues/1050#issuecomment-472315078. This goes back to needing the querysets exposed via a public api (or to continue to abuse the private api).

**Comment by clokep** [comment]
I see. Any idea what that API might look like? Take note that a `QuerySetSequence` can have multiple `QuerySets` of the same model in it.

**Comment by jpic** [comment]
Maybe qss.for_ctype(id=123) could return the querysets that match the
content type ?
Then for the use case in dal, just try the first item of the resulting
queryset list, that would resolve 99% of the use cases in dal. If the user
configures several qs for the same model in their autocomplete field then
it will be up to them to figure out what qs to get the object from.

**Comment by optiz0r** [comment]
>Any idea what that API might look like?

Anything that allows downstream code to extract the component querysets (ideally in order, but not strictly required) would be sufficient for DAL's use case, because they they can continue using the exact same code as now, just accessing the component querysets via a stable public API rather than a private implementation detail.

I don't think you need to care about ContentTypes or how DAL matches objects back to querysets at all.

The bare minimum would be:
```python
# Methods that do not return QuerySets
def get_querysets(self):
    return self._querysets
```

such that
```python
querysets = [a,b,c]
QuerySetSequence(*querysets).get_querysets() == querysets
```

If you ever wanted to change the underlying implementation of storing the querysets as a list on the `_querysets` attribute, this method would just need updating to retain compatibility.

>Take note that a QuerySetSequence can have multiple QuerySets of the same model in it.

Any logic relating to what the querysets do should be left to the downstream code. In DAL's case of using ContentType to reverse which queryset a given object belongs to, that the code only works when ContentTypes are not duplicated across querysets is a limitation that needs to be documented in that project rather than this one. For most users, I don't think this would be an issue (and is certainly no change compared to the QSS==0.7 situation, which is the latest version that DAL presently works with). But again, this isn't something you should have to concern yourself with.

**Comment by clokep** [comment]
@optiz0r I don't think that's enough for the use-case shown in https://github.com/percipient/django-querysetsequence/issues/21#issuecomment-471357194. That generates a new `QuerySetSequence` after trimming each `QuerySet`, but this is going to probably break in weird ways, for example consider this:

```python
>>> A = ['A1', 'A2']; B = ['B1', 'B2']
>>> qss = QuerySetSequence(A, B)
>>> qss = qss.order_by('-num')  # The number, not the letter. These aren't models, but I hope you get the idea.

>>> qss2 = QuerySetSequence(*qss.get_querysets())
>>> list(qss2)
['A2', 'A1', 'B2', 'B1']
```

You'd really want the results to be interleaved, but you lose the overall ordering when you generate the new `QuerySetSequence`. There's a `clone()` method, but I don't think it is public / what help here.

I wonder if what you actually want is a method that lets you call each underlying `QuerySet` with a function?

Something like:

```python
qss.apply_to_querysets(lambda qs: qs[:20])
```

**Comment by optiz0r** [comment]
Ah ha, I see I've confused things by having two separate discussion points in the same thread without clearly noting which one I was referring to in each comment. To clarify, I'll summarise my current position on both here.

DAL makes use of private `_queryset` attribute in two places, both of which I was trying to address:
- Generating unique-IDs for objects retrieved from the API to use in form field values (which needs both the object ID and some form of type, to disambiguate the object type), converting unique-IDs back into objects from submitted forms, and validating that the submitted-ID is indeed described by the QuerySetSequence (for security purposes, to avoid abuse of the form)
- Showing a mixture of results from all component QuerySets while evaluating a slice-limited QuerySetSequence

For the first case, I was looking to use your suggestion to @jpic in https://github.com/percipient/django-querysetsequence/issues/21#issuecomment-432649275. The second I discovered while working on the first case, and is the subject of the first question I asked you about on this thread. Shortly thereafter I found my attempt to fix the first case was fatally flawed and had to revert[0].

The `get_querysets` code I suggested above, and present again below with less short-hand and more context to make it more clear what it's doing, seeks only to address the first case. By exposing the component querysets with this additional public api method, the logic for generating/processing IDs can remain wholly within the DAL project, as it is when using QSS<=0.7.

```python
# Proposed addition:
class QuerySetSequence(ComparatorMixin):
  def get_querysets(self):
    return self._querysets

# example usage
querysets = [ModelA.objects.filter(foo="bar"), ModelB.objects.all()]
qss = QuerySetSequence(*querysets)
# later
components = qss.get_querysets()

# expectation
assert components == querysets
```

Another user of DAL, @monim67, has previously contributed the minimum change to resolve compatibility with 0.9, continuing to use the private `_querysets` attribute directly. The location of this attribute appears to have changed between 0.7 and 0.9 which broke DAL. The suggested fix in PR https://github.com/yourlabs/django-autocomplete-light/pull/1056/files updates the location of the `_querysets` attribute to make DAL work again. The difference between that PR and my `get_querysets` proposal is to make access to `_querysets` explicitly public, to avoid unintentional future incompatibility between the two projects.

As for the second case, if you accept the `get_querysets` proposal, DAL can continue to use the existing logic (perhaps flawed, but good enough for me anyway) without further changes in QSS. If you agree the usecase is sufficiently valuable to add to QSS project, I don't think we've actually reached consensus on how this should be implemented on the QSS side yet.

---
[0] Trying your suggested approach of using queryset index `#` instead of ContentType ID, when trying to to render a form with a previously saved object having, the initial value for the field represented by the QSS is taken directly from the database and has not been annotated with a queryset `#` attribute. There is no way to map this object to a component queryset of the QSS, and therefore no way to generate a valid unique-ID. When using ContentType IDs, the unique identifier is derivable directly from the object, without needing to know anything about the structure of the QSS.

This logic is specific to DAL and you need not concern yourself with it, other than that as a result, DAL cannot replace usage ContentType ID with queryset index as suggested. Your other comments about having multiple component querysets using the same ContentType hold true, and this is indeed a limitation of the code, but not one that I think needs to be dealt with here.

**Comment by clokep** [comment]
@optiz0r I see what you're saying, but I think it is missing a bunch of details, e.g. `_querysets` actually gets re-ordered at points inside of `QuerySetSequence` at certain points. Does that matter?

I think I'd accept a contribution to support this with the right tests and documentation, but I also want to make sure it'll actually solve the use-cases of DAL before supporting it.

**Comment by optiz0r** [comment]
For DAL, reordering is not a problem. In both cases where it needs the queryset, it iterates over the full set and the order is not important. Bear in mind it's already doing exactly this, just not via a supported method.

I'm happy to write a PR for the code changes, and will attempt to update the docs and tests at the same time. I will note in the docs that ordering is not guaranteed, and make sure the test(s) handle this.

Thanks!
